WKWebView and Authorization
Pavel-Laukhin/GitHubClient pull request #3
Opened 2020-10-23 15:42 UTC by Pavel-Laukhin

Hometask №4 is ready!

2020-10-25 10:34 UTC, nskazakov requested changes
Уже видел такой код
Создай ПР в предыдущую ветку или сделай мердж предыдущей

2020-10-25 10:34 UTC, nskazakov commented on GitHubClient/Controllers/HelloViewController.swift
> +        switcher.isOn ? (starsNumberTextField.isEnabled = true) : (starsNumberTextField.isEnabled = false)
ты чего?))

starsLabel.isEnabled = switcher.isOn
starsNumberTextField.isEnabled = switcher.isOn

2020-10-25 13:13 UTC, Pavel-Laukhin commented on GitHubClient/Controllers/HelloViewController.swift
> +        switcher.isOn ? (starsNumberTextField.isEnabled = true) : (starsNumberTextField.isEnabled = false)
Ахахах, точно )))) Все гениальное просто! И чего я сам-то не догадался )))

2020-11-05 15:20 UTC, Pavel-Laukhin commented
Well. I'll try do my best at the Git Flow using my new experience from the game at https://learngitbranching.js.org :]

2020-11-05 15:20 UTC, closed without merging