Feature/task 3/impl
Pavel-Laukhin/GitHubClient pull request #5
Opened 2020-11-05 16:00 UTC by Pavel-Laukhin

Задание номер 3

2020-11-07 05:40 UTC, nskazakov requested changes

2020-11-07 05:40 UTC, nskazakov commented on GitHubClient/Controllers/HelloViewController.swift
> +            }
можно удалить неиспользуемый код

2020-11-07 05:40 UTC, nskazakov commented on GitHubClient/Controllers/ResultTableViewCell.swift
> +}
лучше вынести в отдельный файл

2020-11-07 05:40 UTC, nskazakov commented on GitHubClient/Controllers/ResultTableViewController.swift
> +    }
можно у таблицы определить selectionStyle на none и тогда не придется в делегате в этом методе определять

2020-11-07 05:40 UTC, nskazakov commented on GitHubClient/Models/Repo.swift
> +struct Repo {
почему не Codable?

2020-11-08 18:58 UTC, Pavel-Laukhin commented on GitHubClient/Controllers/ResultTableViewController.swift
> +    }
Исправил, спасибо. Правда не selectionStyle, а allowsSelection, и не на none, а на false. Что-то я не нашел там никакого selectionStyle ((

2020-11-08 18:58 UTC, Pavel-Laukhin commented on GitHubClient/Controllers/ResultTableViewCell.swift
> +}
Вынес, спасибо!

2020-11-08 18:59 UTC, Pavel-Laukhin commented on GitHubClient/Models/Repo.swift
> +struct Repo {
Потому что не разобрался в том, как он работает )) Теперь разобрался, окей ))

2020-11-10 02:57 UTC, nskazakov approved these changes

2020-11-11 15:30 UTC, merged